### ISSUE TITLE
after following the steps still getting some error

### ISSUE THREAD

**Issue by void2241** [oracle/accelerators#2]
![error](https://cloud.githubusercontent.com/assets/17716558/13591934/7a4020ea-e513-11e5-862a-988da4f9d8e4.png)
![errorlog](https://cloud.githubusercontent.com/assets/17716558/13591944/939918e4-e513-11e5-9401-a758d3103d3b.png)

please tell how to resolve this issue

**Comment by rpeace42** [comment]
Please post your questions to the forum on cx.rightnow.com.
You can change the time out in the custom configuration you've loaded to
the server if you're sure that the endpoint is valid.

Roderick

On Mon, Mar 7, 2016 at 9:23 PM, void2241 <notifications@github.com> wrote:

> [image: error]
> <https://cloud.githubusercontent.com/assets/17716558/13591934/7a4020ea-e513-11e5-862a-988da4f9d8e4.png>
> [image: errorlog]
> <https://cloud.githubusercontent.com/assets/17716558/13591944/939918e4-e513-11e5-9401-a758d3103d3b.png>
>
> please tell how to resolve this issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oracle/Accelerators/issues/2>.
>



-- 
Roderick Peace
http://www.linkedin.com/in/rjpeace
Cell 310-529-9716

**Comment by void2241** [comment]
@rpeace42 can you tell me for only connection from OSvC to siebel what are the main thing to be done in the siebel server.

**Comment by void2241** [comment]
http://communities.rightnow.com/posts/6c8f9babac 
@rpeace42  already created in the rightnow but no one is helping

**Comment by brunoborges** [comment]
@rpeace42, any update?

**Comment by rpeace42** [comment]
The Setup guide lists the Siebel custom schema changes and web services that need to be published for the Accelerator to work. http://www.oracle.com/technetwork/indexes/samplecode/accelerator-osvc-2525361.html
